import pygame
import sys
sys.path.append("classes")
from pygame.locals import *
from random import *
import time

import classes_tpt


def savetpt():
    fichier = open("save1\\pv\\pvp1", "w")
    fichier.write(str(perso_joueur.vie))
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp1", "w")
    fichier.write(str(perso_joueur.xp))
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp1", "w")
    fichier.write(str(perso_joueur.niveau))
    fichier.close()
    fichier = open("save1\\pv\\pvp2", "w")
    fichier.write(str(david.vie))
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp2", "w")
    fichier.write(str(david.xp))
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp2", "w")
    fichier.write(str(david.niveau))
    fichier.close()
    fichier = open("save1\\pv\\pvp3", "w")
    fichier.write(str(sinatra.vie))
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp3", "w")
    fichier.write(str(sinatra.xp))
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp3", "w")
    fichier.write(str(sinatra.niveau))
    fichier.close()
    fichier = open("save1\\objet\\fleche", "w")
    fichier.write(str(perso_joueur.fleche))
    fichier.close()
    fichier = open("save1\\objet\\mana", "w")
    fichier.write(str(perso_joueur.mana))
    fichier.close()
    fichier = open("save1\\activation\\sortdefeu", "w")
    fichier.write(str(perso_joueur.sortdefeu))
    fichier.close()
    fichier = open("save1\\activation\\perso3", "w")
    fichier.write(str(sinatra.active))
    fichier.close()
    fichier = open("save1\\objet\\nbresurect", "w")
    fichier.write(str(resurection.quantite))
    fichier.close()
    fichier = open("save1\\objet\\nbsoin", "w")
    fichier.write(str(soin.quantite))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep1", "w")
    fichier.write(str(perso_joueur.ptdecompetance))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep1", "w")
    fichier.write(str(perso_joueur.ptvie))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep1", "w")
    fichier.write(str(perso_joueur.ptforce))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep2", "w")
    fichier.write(str(david.ptdecompetance))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep2", "w")
    fichier.write(str(david.ptvie))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep2", "w")
    fichier.write(str(david.ptforce))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep3", "w")
    fichier.write(str(sinatra.ptdecompetance))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep3", "w")
    fichier.write(str(sinatra.ptvie))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep3", "w")
    fichier.write(str(sinatra.ptforce))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptmana", "w")
    fichier.write(str(perso_joueur.ptmana))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptdodge", "w")
    fichier.write(str(sinatra.ptdodge))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptbouclier", "w")
    fichier.write(str(perso_joueur.ptbouclier))
    fichier.close()


def chargementsauvegarde():
    fichier = open("save1\\pv\\pvp1", "r")
    perso_joueur.vie = int(fichier.read())
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp1", "r")
    perso_joueur.xp = int(fichier.read())
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp1", "r")
    perso_joueur.niveau = int(fichier.read())
    fichier.close()
    fichier = open("save1\\pv\\pvp2", "r")
    david.vie = int(fichier.read())
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp2", "r")
    david.xp = int(fichier.read())
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp2", "r")
    david.niveau = int(fichier.read())
    fichier.close()
    fichier = open("save1\\pv\\pvp3", "r")
    sinatra.vie = int(fichier.read())
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp3", "r")
    sinatra.xp = int(fichier.read())
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp3", "r")
    sinatra.niveau = int(fichier.read())
    fichier.close()
    fichier = open("save1\\objet\\fleche", "r")
    perso_joueur.fleche = int(fichier.read())
    fichier.close()
    fichier = open("save1\\objet\\mana", "r")
    perso_joueur.mana = int(fichier.read())
    fichier.close()
    fichier = open("save1\\activation\\sortdefeu", "r")
    perso_joueur.sortdefeu = fichier.read()
    fichier.close()
    fichier = open("save1\\activation\\perso3", "r")
    sinatra.active = fichier.read()
    fichier.close()
    fichier = open("save1\\objet\\nbresurect", "r")
    resurection.quantite = int(fichier.read())
    fichier.close()
    fichier = open("save1\\objet\\nbsoin", "r")
    soin.quantite = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep1", "r")
    perso_joueur.ptdecompetance = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep1", "r")
    perso_joueur.ptvie = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep1", "r")
    perso_joueur.ptforce = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep2", "r")
    david.ptdecompetance = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep2", "r")
    david.ptvie = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep2", "r")
    david.ptforce = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep3", "r")
    sinatra.ptdecompetance = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep3", "r")
    sinatra.ptvie = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep3", "r")
    sinatra.ptforce = int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptmana", "r")
    perso_joueur.ptmana = int(fichier.read())
    fichier = open("save1\\ptcompetance\\ptdodge", "r")
    sinatra.ptdodge= int(fichier.read())
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptbouclier", "r")
    perso_joueur.ptbouclier= int(fichier.read())
    fichier.close()
    fichier.close()


def resetsauvegarde():
    fichier = open("save1\\pv\\pvp1", "w")
    fichier.write(str(150))
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp1", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp1", "w")
    fichier.write(str(1))
    fichier.close()
    fichier = open("save1\\pv\\pvp2", "w")
    fichier.write(str(200))
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp2", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp2", "w")
    fichier.write(str(1))
    fichier.close()
    fichier = open("save1\\pv\\pvp3", "w")
    fichier.write(str(100))
    fichier.close()
    fichier = open("save1\\niveau+xp\\xpp3", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\niveau+xp\\nivp3", "w")
    fichier.write(str(5))
    fichier.close()
    fichier = open("save1\\objet\\fleche", "w")
    fichier.write(str(10))
    fichier.close()
    fichier = open("save1\\objet\\mana", "w")
    fichier.write(str(100))
    fichier.close()
    fichier = open("save1\\activation\\sortdefeu", "w")
    fichier.write(str(False))
    fichier.close()
    fichier = open("save1\\activation\\perso3", "w")
    fichier.write(str(False))
    fichier.close()
    fichier = open("save1\\objet\\nbresurect", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\objet\\nbsoin", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep1", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep1", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep1", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep2", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep2", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep2", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptcompetancep3", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptviep3", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptforcep3", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptmana", "w")
    fichier.write(str(0))
    fichier = open("save1\\ptcompetance\\ptdodge", "w")
    fichier.write(str(0))
    fichier.close()
    fichier = open("save1\\ptcompetance\\ptbouclier", "w")
    fichier.write(str(0))
    fichier.close()
    fichier.close()
